namespace: allanroque
name: eda_url_content
version: '1.0.0'
authors:
  - Allan Roque <aroque@redhat.com>
description: A custom Event-Driven Ansible plugin for polling URLs and retrieving their status and content.
repository: https://github.com/allanroque/eda_url_content
documentation: https://github.com/allanroque/eda_url_content/tree/main/docs
homepage: https://github.com/allanroque/eda_url_content
license:
  - Apache-2.0
license_file: ""
readme: README.md
tags:
  - infrastructure
  - monitoring
  - automation
  - EDA
  - URL polling
dependencies: {}

build_ignore:
  - "demos"
  - ".venv"
  - "venv"